[build-system]
requires = [
    "setuptools>=64.0.0",
    "setuptools-scm[toml]",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "fritz-ds"
authors = [{name = "Fritz Morgendorfer", email = "fritz.morgendorfer@gmail.com"}]
description = "Self-implemented stuff in the field of DS/ML."
classifiers = [
    "Programming Language :: Python :: 3.11"
]
requires-python = ">=3.11, <3.12"
dynamic = ["version", "dependencies", "optional-dependencies"]

[project.scripts]
pipe = "fritz_ds_lib.cli.app:cli"

[tool.setuptools]
include-package-data = true
package-dir = { "" = "src" }

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
dev = {file = ["requirements-dev.txt"]}

# automatically find packages
[tool.setuptools.packages.find]
where = ["src"]
namespaces = true

[tool.ruff]
line-length = 89

[tool.ruff.lint]
extend-select = ["E501", "F401"]
select = ["T201"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "fritz", "local-folder"]

[tool.ruff.lint.isort.sections]
fritz = ["fritz_ds_lib, fritz_ds_pipe"]

[tool.mypy]
plugins = ["pydantic.mypy"]
files = ["src", "tests"]
mypy_path = ["src"]
explicit_package_bases = true
